pipeline{

    agent any
    environment{
        projetoJK = "$WORKSPACE/Prova_N2_2_app_fast"
    }
    stages{
        stage('Wrapper'){
            steps{
                echo 'Criando Ambiente Workspace'
                dir("$projetoJK"){
                    sh 'gradle wrapper'
                }
            }
        }
        stage('Teste Unit'){
            steps{
                echo 'Rodando todos os Testes'
                dir("$projetoJK"){
                    sh './gradlew test '
                }
            }
        }
        stage('Construindo APK'){
            steps{
                echo 'Etapa gerando APK'
                dir("$projetoJK"){
                    sh './gradlew assembleRelease'
                }
            }
        }
        stage('Arquivando APK'){
            steps{
                echo 'arquivando apk gerado'
                archiveArtifacts artifacts: '**/app-release-unsigned.apk', fingerprint: true, allowEmptyArchive: false
                echo'Arquivado com Sucesso!'
            }
        }
    }
}