pipeline{

    agent any
    environment{
        projetoJK = "$WORKSPACE/Prova_N2_2_app_fast"
    }
    stages{
        stage(''){
            steps{
                echo ''
                dir("$projetoJK"){
                    sh '$projetoJK/gradle wrapper'
                }
            }
        }
    }
}