pipeline{

    agent any
    environment{
        projetoJK = "$WORKSPACE/Prova_N2_2_app_fast"
    }
    stages{
        stage('Wrapper'){
            steps{
                echo 'Criando Ambiente Workspace'
                dir("$projetoJK"){
                    sh 'gradle wrapper'
                }
            }
        }
    }
}